const version = "V1.0"; // Version of the application (info)
const versionFvm = "3.2.1"; // Version FVM (info)
const versionFlutter = "3.29.2"; // Version Flutter (info)
const versionDartSdk = "3.7.2"; // Version DartSDK (info)
const versionDevTools = "2.42.3"; // Version DevTools(info)
const nomecatalogo = "Moveis3F1B"; // Nome do catálogo
// const databaseFW = "3F1B"; // Nome do database ForWood
const databaseFW = "TESTE3F"; // Nome do database ForWood
const hostFW = "192.168.10.213";
// const hostFW = "localhost"; // Nome do host ForWood
const portFW = 5432; // Nome da porta ForWood
const userNameFW = "postgres"; // Usuario do banco de dados ForWood
const passwordFW = "postgres"; // Senha do banco de dados ForWood
const codbatismocorte = "42"; // Código de batismo do corte
const codbatismomodulo = "4.1"; // Código de batismo do módulo
const codbatismopedido = "5.3"; // Código de batismo do pedido
const codUMM2 = "M2"; // Código da unidade de medida M2
const codUMM3 = "M3"; // Código da unidade de medida M3
const hostSQL = 'NOTEDARTT\\ECADPRO2019'; // Nome do host SQL Server
// const hostSQL = 'servercad\\ECADPRO2014'; // Nome do host SQL Server (antigo)
const portSQL = '1433'; // Porta do SQL Server
const databaseSQL = 'Moveis3F1B'; // Nome do banco de dados SQL Server
const userNameSQL = 'sa'; // Usuário do SQL Server
const passwordSQL = 'eCadPro2019'; // Senha do SQL Server
// const passwordSQL = 'eCadPro2014'; // Senha do SQL Server (antigo)
const diretorioXML = "T:\\xml";
//const diretorioXML =
//    "C:\\evolution\\xml"; // Diretório onde estão os arquivos XML
const diretorioESP = "C:\\industrial\\"; // Diretório onde estão os arquivos ESP
